### PR TITLE
Remove dead code to remove warnings

### PR DESCRIPTION
**Pull request by bwilkerson**
@lukechurch

### CODE REVIEW

**Comment by bwilkerson** [comment]
There are also warnings in `session_ldap.dart` (lines 17 and 31) because `sessionIdComparator` (https://github.com/lukechurch/sintr/blob/master/analysis_server_example/lib/query/session_ldap.dart#L11) is declared as `(String, String) -> double` but it's being passed in to a method that is expecting a `(dynamic, dynamic) -> int`. The arguments types are not as big a deal (though I do think it should be fixed), but it's somewhat concerning to me that the return type is inconsistent.

I'm not sure how to resolve this, but I can propose something if you'd like.

**Comment by lukechurch** [comment]
@danrubel I think this was your code originally? Do you have any comments on what Brian is saying?

**Comment by danrubel** [comment]
Cleaning up the argument types sgtm.

**Comment by bwilkerson** [comment]
> Cleaning up the argument types sgtm.

Ok, but how? Will the parameters always be strings, or does `sessionIdComparator` need to be fixed to handle the possibility that they won't be? (And if the latter, what else might they be?) Are the values of the strings really floating point numbers, or are they really integers?

**Comment by danrubel** [comment]
The output can be normalized to num so that it can have the states >0, ==0, <0. I *think* that the inputs are always Strings, but not sure... @lukechurch ?

**Comment by bwilkerson** [comment]
We could merge this PR and then I could make another PR for the remaining warnings...

**Comment by danrubel** [comment]
Sorry... yes... makes sense... should have given you LGTM immediately.

**Comment by danrubel** [comment]
LGTM

**Comment by bwilkerson** [comment]
No problem; it didn't occur to me until part way through the discussion either.

**Comment by bwilkerson** [comment]
@lukechurch ping (re: Dan's question about whether the arguments will always be strings)

**Comment by lukechurch** [comment]
@bwilkerson Sorry for the delay. I see no reason why we can't make that decision and state that they always will be strings.

**Comment by bwilkerson** [comment]
Sounds good. I'll try to put out a PR soon.

My hesitancy related to doing so was purely based on a lack of understanding on my part of where the data comes from. :-)

**Comment by bwilkerson** [comment]
@lukechurch @danrubel I added changes for the remaining errors and warnings. PTAL.

**Comment by danrubel** [comment]
LGTM

**Comment by lukechurch** [comment]
LGTM

**Pull request merged**
